public class example5 {
    //addition ,substraction ,multiplication,division
    public static void addition(integer a,integer b){
        system.debug('the addition of two number is '+(a+b));
    }
    public static void substraction(integer c, integer d){
        system.debug('the substraction of two number is '+(c-d));
    }
    public static void multiplication(integer e,integer f){
        system.debug('the multiplication of two number is '+(e*f));
    }
    public static void divison(integer g,integer h){
        system.debug('the divison of two number is '+(g/h));
    }

}