public class Paramatrized_programms {
    public static void test(integer x,integer y){
        system.debug('the addition is '+(x+y));
        system.debug('the substraction is '+(x-y));
        system.debug('the multiplication is '+(x*y));
        system.debug('the divison is '+(x/y));
    }
    public static void test1(string s1,string s2){
        if(s1==s2){
            system.debug('both are identicle');
        }
        else{
            system.debug('both are different');
        }
    }
    
}