public class sub4 {
    public static void test(integer x, integer y){
        //perform all mathematicle operation
        system.debug('the addition of two number is '+(x+y));
        system.debug('the substraction of two numebr'+(x-y));
        system.debug('the multiplication of two number'+(x*y));
        system.debug('the division of two number is '+(x/y));
    }
    public static void test(string a, string b){
        if(a==b){
            system.debug('both are identicle');
        }
        else{
            system.debug('both are different');
        }
    }

}